version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: some-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web-app:
    image: neildudani/trent-app
    depends_on:
      - db
    ports:
      - '4444:4444'
